# Generated by Django 5.2.3 on 2025-06-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='user_logo/')),
                ('gallery_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
