# Generated by Django 5.2.3 on 2025-06-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='gallery_link',
        ),
    ]
