# Generated by Django 5.2.3 on 2025-07-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPB', '0003_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='mail',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
