# Generated by Django 5.2.3 on 2025-07-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPB', '0004_portfolio_address_portfolio_mail_portfolio_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
