# Generated by Django 5.2.6 on 2025-09-20 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPB', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_img',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/project/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills',
            field=models.TextField(default='', help_text='Comma separated skills'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tech_stack',
            field=models.TextField(default='', help_text='Comma separated technologies'),
        ),
    ]
